export const LOAD_SONGS_SUCCESS = "LOAD_SONGS_SUCCESS";

export const PLAY_SONG = "PLAY_SONG";
export const CHANGE_SONG = "CHANGE_SONG";
export const PAUSE_SONG = "PAUSE_SONG";
export const VOLUME_CHANGE = "VOLUME_CHANGE";
export const POSITION_CHANGED = "POSITION_CHANGED";
export const POSITION_CHANGED_FROM_SLIDER = "POSITION_CHANGED_FROM_SLIDER";
export const PLAY_PREV_SONG = "PLAY_PREV_SONG";
export const PLAY_NEXT_SONG = "PLAY_NEXT_SONG";
